# -*- coding: utf-8 -*-
"""project107.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PyeWC__oVpK8rIshY3C1V_4wGlYqOzGg
"""

import pandas as pd
import plotly.express as px
df = pd.read_csv("https://raw.githubusercontent.com/whitehatjr/Data-Analysis-by-visualisation/master/data.csv")
print(df)

grp = df.groupby("level")["attempt"].mean()
print(grp)

fig = px.bar(df,x = ["level 1","level 2","level 3", "level 4"],y = grp)
fig.show()

student1 = df[df["student_id"]=="TRL_xsl"]
student1_data = student1.groupby("level")["attempt"].mean()
print(student1_data)

fig = px.bar(df,x = ["level 1","level 2","level 3", "level 4"],y = student1_data)
fig.show()